CREATE TABLE IF NOT EXISTS urls (
    id    SERIAL PRIMARY KEY,
    code  VARCHAR(10) UNIQUE NOT NULL,
    url   TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_urls_code ON urls(code);
